export enum ConfigEnum {
  TEMPLATE_DIR = 'TEMPLATE_DIR',
  AMQP_SERVERS = 'AMQP_SERVERS',
  IAM_ACCESS_KEY = 'IAM_ACCESS_KEY',
  IAM_SECRET_KEY = 'IAM_SECRET_KEY',
  AWS_REGION = 'AWS_REGION',
  IDENTITY_NAME = 'IDENTITY_NAME',
}
